"""Initial migration

Revision ID: 480ce99b0465
Revises: 
Create Date: 2026-06-17 13:40:13.076620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480ce99b0465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_words',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('anchor_word', sa.String(length=100), nullable=False),
    sa.Column('anchor_similarity', sa.Float(), nullable=False),
    sa.Column('anchor_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_key', sa.String(length=50), nullable=False, comment="Machine key, e.g. 'streak_7', 'under_3'"),
    sa.Column('achievement_name', sa.String(length=100), nullable=False, comment="Human-readable name, e.g. 'Week Warrior'"),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_key', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_achievements_achievement_key'), 'achievements', ['achievement_key'], unique=False)
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | accepted | blocked'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    op.create_index('ix_friendships_addressee', 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False, comment='daily | freeplay'),
    sa.Column('target_word', sa.String(length=100), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('hints_used_count', sa.Integer(), nullable=False),
    sa.Column('penalty_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'game_type', name='uq_user_daily_game')
    )
    op.create_index(op.f('ix_game_sessions_day'), 'game_sessions', ['day'], unique=False)
    op.create_index('ix_game_sessions_day_won', 'game_sessions', ['day', 'won'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('guesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('guess_number', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('raw_similarity', sa.Float(), nullable=False),
    sa.Column('scaled_similarity', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('guessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word', name='uq_guess_session_word')
    )
    op.create_index(op.f('ix_guesses_session_id'), 'guesses', ['session_id'], unique=False)
    op.create_table('hints_used',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('hint_number', sa.Integer(), nullable=False),
    sa.Column('hint_word', sa.String(length=200), nullable=False),
    sa.Column('hint_rank', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hints_used_session_id'), 'hints_used', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hints_used_session_id'), table_name='hints_used')
    op.drop_table('hints_used')
    op.drop_index(op.f('ix_guesses_session_id'), table_name='guesses')
    op.drop_table('guesses')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index('ix_game_sessions_day_won', table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_day'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index('ix_friendships_addressee', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_key'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('daily_words')
    # ### end Alembic commands ###
